services:
  - type: web
    name: pirateone
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn pirateone_backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: pirateone_backend.settings
