services:
- type: web
  name: pirateone
  env: python
  buildCommand: |
    pip install -r requirements.txt
    python manage.py collectstatic --noinput
    python manage.py migrate
  startCommand: gunicorn pirateone_backend.wsgi:application
  envVars:
    - key: DJANGO_SETTINGS_MODULE
      value: pirateone_backend.settings
